project:
  type: website
  output-dir: docs
website:
  title: "Genomics Workshop 2022"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Day 1"
        file: Day1.qmd
      - text: "Day 2"
        file: Day2.qmd
      - text: "Day 3"
        file: Day3.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual
server: shiny
